package hotciv.variants.strategies;

import hotciv.common.BaseGame;
import hotciv.common.GameWorld;
import hotciv.common.strategy.WorldLayoutStrategy;
import hotciv.variants.AlphaCiv;
import thirdparty.ThirdPartyFractalGenerator;

/**
 * Creates the world layout generated by the ThirdPartyFractalGenerator.
 *
 * @author Erik
 *         Created: 16-11-12, 10:25
 */
public class FractalWorldLayout implements WorldLayoutStrategy {
    private BaseGame game;

    public FractalWorldLayout(BaseGame game) {
        this.game = game;
    }

    @Override
    public void createWorldLayout() {
        GameWorld gameWorld = game.getGameWorld();

        String[] worldLayout = new String[16];

        ThirdPartyFractalGenerator generator =
                new ThirdPartyFractalGenerator();
        String line;
        for (int r = 0; r < 16; r++) {
            line = "";
            for (int c = 0; c < 16; c++) {
                line = line + generator.getLandscapeAt(r, c);
            }
            // Making it fit out definition of the world.
            line = line.replaceAll("o", "P").replaceAll("\\.", "O").toUpperCase();
            worldLayout[r] = line;
        }

        gameWorld.populateWorld(worldLayout);
    }

    public static void main(String[] args) {
        new FractalWorldLayout((BaseGame) new AlphaCiv().newGame()).createWorldLayout();
    }
}
